SocialGouv/kali-data

- __tests__/__snapshots__/astify.test.js.snap
- __tests__/__snapshots__/filterData.test.js.snap
- __tests__/astify.test.js
- __tests__/filterData.test.js
- __tests__/kaliCont-sample.json
- package.json
- scripts/fetch-ccns.js
- src/astify.js
- src/filterData.js
- src/kalicont-sample.js
- src/kalicont-sample.json
- yarn.lock
- externalize some code
- add some Snapshots/TUs
> feat: tests

- data/index.json
> fix: add IDCC 1740

- scripts/fetch-ccns.js
this prevent producing +10k job logs
> chore: remove some log

- scripts/fetch-ccns.js
fix (I hope this time for real) the text order
> fix: sort text in ast too

- .gitlab-ci.yml
- scripts/fetch.js
> fix(fetch): more retries

- src/index.js
> refactor: remove useless types reference

- scripts/libs/__tests__/__snapshots__/astify.test.js.snap
- scripts/libs/__tests__/astify.test.js
- scripts/libs/astify.js
> fix(data): dedup kali section

- src/index.d.ts
- add `cid` to type `AgreementSectionData`
> fix: add cid to AgreementSectionData type

- data/index.json
- src/index.d.ts
see :  https://github.com/SocialGouv/code-du-travail-numerique/issues/3063
> feat(data): add synonyms

- scripts/helpers/getArticlePath.js
trying to fix https://gitlab.factory.social.gouv.fr/SocialGouv/kali-data/-/jobs/1380380
> fix(fetch): prevent exception

- data/IDCC3239.json
- data/index.json
fixes https://github.com/SocialGouv/code-du-travail-numerique/issues/4089
> feat: add the CC 3239 (no legifrance url at this moment)

- data/index.json
> feat: add effectif on agreement 3239

- data/index.json
fix https://github.com/SocialGouv/code-du-travail-numerique/issues/4098
> feat: 3239 is effective

- data/KALICONT000005635842-3209.json
- data/index.json
fix https://github.com/SocialGouv/code-du-travail-numerique/issues/4103
> fix: rename cc 1809 -> 3231 and 1375 -> 3209 

- data/KALICONT000005635870.json
- data/index.json
Fix https://github.com/SocialGouv/code-du-travail-numerique/issues/4490
> feat(cc 1517): rename CC

- data/KALICONT000005635905.json
- data/index.json
Ajout d'une CC manquante dans les données : IDCC 1413, cf #256
> feat: add IDCC 1413

- data/index.json
refer to https://github.com/SocialGouv/code-du-travail-numerique/issues/5213
> feat(ccn): ajout d'un synonyme pour la CC 1486

- data/KALICONT000005635725.json
- data/index.json
- update-cc/data-cc/idcc_liens.xlsx
fix [#5363](https://github.com/SocialGouv/code-du-travail-numerique/issues/5363)
> feat(cc): ajout de la CC 804

- data/index.json
- update-cc/data-cc/idcc_sans_liens.xlsx
- update-cc/index.ts
- update-cc/infos.ts
- update-cc/types.ts
refer to https://github.com/SocialGouv/code-du-travail-numerique/issues/5315
> feat(ccs): ajouts des ccs qui n'ont pas de liens vers légifrance

- data/index.json
Fix [Synonymes à ajouter pour 2 CC#5541](https://github.com/SocialGouv/code-du-travail-numerique/issues/5541)
> feat: ajout de synonymes pour les CC 413 et 29

- data/index.json
Fix https://github.com/SocialGouv/code-du-travail-numerique/issues/5544
> fix(métallurgie): ajout de l'effectif à la métallurgie afin que cette dernière remonte bien dans les résultats de recherche

- data/index.json
Fix https://github.com/SocialGouv/code-du-travail-numerique/issues/5609 et https://github.com/SocialGouv/code-du-travail-numerique/issues/5608
> feat(convention collective): Intégration de la CC 1543 dans la CC 1586 et Intégration de la CC 2344 dans la CC 3248
